baseURL = 'https://www.RaffaeleBianco.it/blog/'
languageCode = 'it-it'
title = 'Mica scrivo granché'
theme = 'hugo-theme-stack'
enableEmoji = true

paginate = 5
copyright = "Raffaele Bianco"
DefaultContentLanguage = "it"
hasCJKLanguage = false

[languages.it]
languageName = "Italiano"
title = "Mica scrivo granché"
weight = 1

  [languages.it.params]
  description = "Blog di Raffaele Bianco"

# [languages.en]
# languageName = "English"
# title = "Raffaele Bianco's Blog"
# weight = 2

#   [languages.en.params]
#   description = ""

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_004

  [params.dateFormat]
  published = "02/01/2006"
  lastUpdated = "02/01/2006 15:04 MST"

  [params.sidebar]
  emoji = ""
  subtitle = ""

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "disqus"

    [params.comments.disqusjs]
    shortname = []
    apiUrl = []
    apiKey = []
    admin = []
    adminLabel = []
    
    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
    requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.cactus]
    defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
    serverName = "cactus.chat"
    siteName = ""

    [params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

    [params.comments.gitalk]

    [params.comments.cusdis]

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 3

# [[params.widgets.homepage]]
# type = "tag-cloud"

#   [params.widgets.homepage.params]
#   limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "facebook"
  name = "Facebook"
  url = "http://facebook.com/RaffaeleBianco"

    [menu.social.params]
    icon = "brand-facebook"
  
  [[menu.social]]
  identifier = "instagram"
  name = "Instagram"
  url = "http://instagram.com/RaffaeleBianc0"

    [menu.social.params]
    icon = "brand-instagram"

  [[menu.social]]
  identifier = "youtube"
  name = "Youtube"
  url = "http://youtube.com/RaffaeleBianco"

    [menu.social.params]
    icon = "brand-youtube"

  [[menu.social]]
  identifier = "ytmusic"
  name = "YouTube Music"
  url = "http://music.youtube.com/channel/UCMwsz2fHAaRfeoezKfp0I0g"

    [menu.social.params]
    icon = "player-play"

  # [[menu.social]]
  # identifier = "github"
  # name = "GitHub"
  # url = "http://github.com/RaffaeleBianc0"

  #   [menu.social.params]
  #   icon = "brand-github"

  [[menu.social]]
  identifier = "linkedin"
  name = "Linkedin"
  url = "http://linkedin.com/in/RaffaeleBianco"

    [menu.social.params]
    icon = "brand-linkedin"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
